### ISSUE TITLE
Using scrape in artoo.spiders

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/artoo#209]
Hello @suntong001,
Does this [example](http://medialab.github.io/artoo/hacker_news/#more) help you?

**Comment by suntong001** [comment]
Thanks for the reply. I saw

```javascript
artoo.ajaxSpider(
  function(i, $data) {
    return nextUrl(!i ? artoo.$(document) : $data);
  },
  {
    limit: 2,
    scrape: scraper,
``` 

I..e, I saw a scraper there, but I can't figure out how the second-step scraping is specified and how it works.

**Comment by Yomguithereal** [comment]
```js
artoo.ajaxSpider(

  // This function is an iterator.
  // Its aim is to return the next url to fecth or false if you want to stop
  //-- 'i' is the index in the iteration of urls
  //-- '$data' is the jQuery-parsed data of the last fetched url
  function(i, $data) {

    // nextUrl is a function that take a jQuery selector and returns
    // the next url to fetch

    // If !i then, we are only starting the spider meaning that the next url
    // is available on the current page rather than the last fetched one.
    return nextUrl(!i ? artoo.$(document) : $data);
  },

  // Spider's settings
  {

    // We want to fetch a maximum of two pages
    limit: 2,

    // We are going to scrape the pages using the scrape definition written above in the doc example
    scrape: scraper,

    // We want to concatenate results so we have [title1, title2, title3, title4]
    // rather than [[title1, title2], [title3, title4]]
    concat: true,

    // Final callback fired when the spider retrieved everything
    //-- 'data' is the scraped data
    done: function(data) {
      artoo.log.debug('Finished retrieving data. Downloading...');
      artoo.savePrettyJson(
        frontpage.concat(data),
        {filename: 'hacker_news.json'}
      );
    }
  }
);
 ```

**Comment by suntong001** [comment]
Oh, thank you, thank you. 
I was just about to say, that it is helping, having been staring it long enough. Your comment make it very clear now. Thank!

**Comment by suntong001** [comment]
The only thing left not so clear to me is how the data flow -- I was trying to guess the relationship between the keyword `data` in `var scraper` and in `done: function(data)`, and `frontpage.concat(data)`. Also I'm not sure where the `$data` comes from in `function(i, $data)`. My guess that none of them are related, but brings up a more important question, how the data are actually passed around? Thanks.

**Comment by Yomguithereal** [comment]
The `data` keyword in `var scraper` works like a named argument because this is what the `scrape` methods expects when you use it with only one argument.

In `done: function(data)`, data is the aggregation of the spider's retrieved data.

`$data` in the iterator function is the html of the last page retrieved by the spider and parsed by jQuery (this is why `$` is used).

**Comment by suntong001** [comment]
Got you. Please close. Thanks. 
BTW, [wiki](https://github.com/medialab/artoo/wiki/Using-scrape-in-artoo.spiders) updated.

**Comment by suntong** [comment]
Hi again Yomguithereal, 

I tried the `artoo.ajaxSpider` for the first time, but I only get the first page result. I.e., the spider is not working. Can you see what I'm doing wrong please? Here is the code:

    var dmList = artoo.scrape('tr td a[href*="edit_domain_id"]', {
      domain: 'text'
    });

    artoo.ajaxSpider(
      function(i) {
	return 'http://freedns.afraid.org/domain/registry/?sort=2&q=.us&page=' + (i+1);
      },
      {
	scrape: dmList,
	limit: 9,
	concat: true,
	throttle: 500,
	done: function(data) {
	  artoo.log.debug('Finished retrieving data. Downloading...');
	  artoo.saveCsv(dmList);
	}
      }
    );

I.e., if you visit http://freedns.afraid.org/domain/registry/?sort=2&q=.us&page=1, then you will see that there will be 9 pages altogether, but I only got one. What's wrong? 

Thanks

**Comment by Yomguithereal** [comment]
The option you are passing to the scrape property is not valid @suntong. What you should really be doing is the following.

```js

var definition = {
  iterator: 'tr td a[href*="edit_domain_id"]',
  data: {domain: 'text'} 
};

var initialList = artoo.scrape(definition);

artoo.ajaxSpider(
  function(i) {
    return 'http://freedns.afraid.org/domain/registry/?sort=2&q=.us&page=' + (i+1);
  },
  {
scrape: definition,
limit: 9,
concat: true,
throttle: 500,
done: function(data) {
artoo.log.debug('Finished retrieving data. Downloading...');
artoo.saveCsv(initialList.concat(data));
}
  }
);
```

**Comment by suntong** [comment]
Oh, thanks a lot, I had always been wondering how the data flow. Now everything is clear. Thanks.
