### ISSUE TITLE
built/artoo.chrome.js can't found

### ISSUE THREAD

**Issue by lukelee36** [medialab/artoo#235]
Hello
I'm traing to use your google chrome extention and if I want to try it on some web then console log wrote me this:

<b>chrome-extension://jbdlbhgaclblcbjidlmddacfpobieodi/build/artoo.chrome.js Failed to load resource: net::ERR_FILE_NOT_FOUND<b>

Do you know what is going on ?

**Comment by Yomguithereal** [comment]
Hello @lukelee36. Did you build the project's file before loading the extension?

**Comment by lukelee36** [comment]
I followed the steps in the manual here: http://medialab.github.io/artoo/chrome/ . Whitch file I have to build befor loading extention ?

**Comment by Yomguithereal** [comment]
If you followed these instructions:

```js
// Clone artoo's repo
git clone https://github.com/medialab/artoo
cd artoo
npm install
gulp
```

Then the file should have been built. Did any error occur during this process?

**Comment by lukelee36** [comment]
I thnig that I had problem with gulp. After I arriwed home. I make it again.

**Comment by lukelee36** [comment]
I tried it again. I have trouble with install <i>phantom.js</i> during instalation <b>npm install</b> and terminal wasnt reacted with <b>gulp</b> at all.

**Comment by Yomguithereal** [comment]
Ok. Can you give me your node & npm version please?
