### ISSUE TITLE
Chrome extension gives an error when loaded about a key file .pem

### ISSUE THREAD

**Issue by lebsral** [medialab/artoo#236]
artoo 0.3.2
The client-side scraping companion.
Permissions Reload (⌘R)
ID: pigfcaeogecjmabjkhcihabfeelgngbe
Loaded from: ~/mycode/artooe/artoo
Inspect views: background page
There were warnings when trying to install this extension:
This extension includes the key file '/Users/lars/mycode/artooe/artoo/node_modules/gulp-webserver/ssl/dev-key.pem'. You probably don't want to do that.

**Comment by Yomguithereal** [comment]
Hello @lebsral. This is a problem with the [gulp-webserver](https://www.npmjs.com/package/gulp-webserver) dependency that packs a pair of keys that are handy when developing. This is not really

**Comment by lebsral** [comment]
Perhaps the manifest file could be moved.

Currently manifest.json is in the root of the project so everything in node_modules directory gets included with the loading of the extension, including the .pem file.

Here is an example chrome extension templates that move the manifest.json inside the src and the build.
https://github.com/yeoman/generator-chrome-extension

Something like that would be a major restructuring of the structure of the project.  Let me know if you want me to work up some pull requests.

**Comment by ataulmustafa** [comment]
I am facing the same issue, as I was working on the unpacked extension loaded in chrome. It shows following errors

There were warnings when trying to install this extension:
This extension includes the key file '\node_modules\public-encrypt\test\test_key.pem'. You probably don't want to do that.
This extension includes the key file '\node_modules\public-encrypt\test\test_rsa_privkey.pem'. You probably don't want to do that.
This extension includes the key file '\node_modules\public-encrypt\test\test_rsa_pubkey.pem'. You probably don't want to do that.
This extension includes the key file '\node_modules\eventsource\test\key.pem'. You probably don't want to do that.

Any idea how to avoid these warnings.

**Comment by ashitvora** [comment]
@ataulmustafa were you able to fix this issue?

**Comment by blksmr** [comment]
anyone found a solution ?

**Comment by Lil-C0der** [comment]
> anyone found a solution ?

Have you solved this problem yet?

**Comment by neso613** [comment]
I am also dealing with same error?

**Comment by Lil-C0der** [comment]
> I am also dealing with same error?

I don’t really know what your issue, but I eventually deleted the .pem file in  /public-encrypt/test. And it works for me.

**Comment by anjalihi** [comment]
Move the .pem file out of the folder that has the manifest and rest of files. Then do Pack Extension and select the key from new location of .pem file.
