### ISSUE TITLE
Uncaught ReferenceError: artoo is not defined

### ISSUE THREAD

**Issue by deenz** [medialab/artoo#241]
I have been using artoo for the last few days and all was fine. However, sometimes an Uncaught Reference Error occurs. Chrome seems to forget about artoo somehow. Could it have something to do with this: http://stackoverflow.com/questions/2075337/uncaught-referenceerror-is-not-defined?

**Comment by Yomguithereal** [comment]
Hello @deenz. On which pages would this error occur? I remember a bug on chrome if there already exists a DOM node with an id "artoo".

**Comment by deenz** [comment]
Hi @Yomguithereal. I tried this morning on the same pages on which it was happening, but it seems to be working fine now! So it's an intermittent bug I think. Previously on the same pages when I started using artoo it was fine as well. So I will let you know if it happens again. And I will try to replicate it so you can see it happening as well (if I can). Thanks!

**Comment by Yomguithereal** [comment]
Ok @deenz. I'll close the issue for now but don't hesitate to reopen if it happens again :)
