### ISSUE TITLE
Save to location

### ISSUE THREAD

**Issue by cy59** [medialab/artoo#248]
Is there a way to specify the file location?  I know I can choose the filename, but having trouble choosing the directory.

**Comment by boogheta** [comment]
I don't think this is something you can do programmatically for browser security reasons.
You can only set separately the default destination of downloaded files for you whole browser before your scraping session.

**Comment by Yomguithereal** [comment]
Yes, @boogheta is right. Browser cannot do that for security reasons. Else the browser would be able to write virtually anywhere on the user's hard drive and this would be really bad.
