### ISSUE TITLE
ajaxSpider does not correctly work with scrapeOne

### ISSUE THREAD

**Issue by GarySiu** [medialab/artoo#264]
If you specify `scrapeOne` in the `ajaxSpider` params, it attempts to use values in `params.scrape` to configure the method. This leads to the error `Uncaught TypeError: Cannot read property 'iterator' of undefined`. I'm sorry I haven't written a PR but I'm not confident in the quality of my solution.

https://github.com/medialab/artoo/blob/facc765f9ec015e26d570680756140c5c3650915/src/methods/artoo.methods.ajaxSpider.js#L61

**Comment by Yomguithereal** [comment]
Hello @GarySiu. I remember tackling this issue but something was amiss. Can you submit your PR on the repo so we can work this out together?

**Comment by GarySiu** [comment]
Created #265. Should probably write a test to cover it but not sure where.
