### ISSUE TITLE
Inject into iframe, not main page

### ISSUE THREAD

**Issue by cizky** [medialab/artoo#268]
Quick question if I may: I am attempting to scrape a site making use of iframes. When injecting artoo.js via the bookmarklet, artoo.js is injected in the top-level context and is not present in a lower (iframe) context.

I have been able to get around this by running the bookmarklet code straight in the required context using the Google Chrome Developer Console. However, I cannot figure out how to automate this just yet, i.e. perhaps create a bookmarklet specifically for that site that would target the required context.

**Comment by Yomguithereal** [comment]
Hum... I guess the possibility to use artoo on the frame context depends on whether the iframe hit an url on the same domain. Is that and old school site using frames for its layout? If this is the case, then jquery is able to access the iframe dom and you should therefore be able to use artoo. If not, you'll probably need some level of chrome extension yes.

**Comment by cizky** [comment]
Many thanks! Your answer pointed me in the right direction. I had troubles scraping the iframe from the 'top' context because the page itself is split into multiple frames. So artoo couldn't see the iframe; it had to be guided down the correct path. In the end, I ended up with this to refer to the specific frame I'm interested in:

$('#iFrame', window.parent.frames[1].document).contents().find('#Grid .grid-row').scrape()

**Comment by Yomguithereal** [comment]
Yup, this should work indeed. If the frame refers to the same domain you are safe. Else things will get difficult.

**Comment by cizky** [comment]
Many thanks the quick response!
