### ISSUE TITLE
Using Artoo with Google Puppeteer 

### ISSUE THREAD

**Issue by jasan-s** [medialab/artoo#271]
How can I use Artoo with [Puppeteer](https://github.com/GoogleChrome/puppeteer). I tried npm install artoo-js , it did not work. should I tried injecting the following  scripts as well `\node_modules\artoo-js\build\artoo.concat.js`  and `\node_modules\artoo-js\build\artoo.chrome.js`     but nothing

**Comment by Yomguithereal** [comment]
Yes, this is not as straightforward. Check how I used to inject artoo with PhantomJS [here](https://github.com/medialab/sandcrawler/blob/master/phantom/bindings.js#L59-L90).

**Comment by Yomguithereal** [comment]
This should be more or less the same idea with puppeteer I think.

**Comment by jasan-s** [comment]
@Yomguithereal  I tried using `page.injectFile(filePath)` from puppeteer and using the phantom js code.  No luck. However I was able to successfully inject query using `page.addScriptTag(url)`.  Not sure  how many others are trying to use it with Puppeteer, but I would find an example really useful.

**Comment by Yomguithereal** [comment]
Pupeteer is quite recent so I am not sure anyone has tried yet. Can you check if injecting artoo phantom's code throw something? I think artoo checks if it is run in a phantomjs scope which it's not in this case. You'll need to edit the code in artoo.phantom

**Comment by jasan-s** [comment]
This worked: first download `wget https://medialab.github.io/artoo/public/dist/artoo-latest.min.js`
then inject it in code like so:  
```
const puppeteer = require('puppeteer');
(async() => {
    const url = 'https://news.ycombinator.com/';
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    // Go to URL and wait for page to load
    await page.goto(url, {waitUntil: 'networkidle'});
    // Inject Artoo into page's JS context
    await page.injectFile('artoo-latest.min.js');
    // Sleeping 2s to let Artoo initialize (I don't have a more elegant solution right now)
    await new Promise(res => setTimeout(res, 2000))
    // Use Artoo from page's JS context
    const result = await page.evaluate(() => {
        return artoo.scrape('td.title:nth-child(3)', {
            title: {sel: 'a'},
            url: {sel: 'a', attr: 'href'}
        });
    });
    console.log(`Result has ${result.length} items, first one is:`, result[0]);
    browser.close();
})();
```
