### ISSUE TITLE
Best practice using Artoo.js to loop through html table

### ISSUE THREAD

**Issue by dataSQL** [medialab/artoo#277]
There is a LIST table with a href link to a DETAIL page.  What would be the best approach to LOOP through each click of the href link and retrieve the detail page?

Any Artoo.js examples greatly appreciated.

**Comment by Yomguithereal** [comment]
A combination of `artoo.scrapeTable` and `artoo.ajaxSpider` seems to be the way to go. Unfortunately I don't have enough time to show you code examples right now.

**Comment by dataSQL** [comment]
Thank you.
