### ISSUE TITLE
Getting Chrome extension to work on linkedin.com

### ISSUE THREAD

**Issue by younkim** [medialab/artoo#286]
I'm trying to use artoo.js (Chrome extension) on Linkedin profile pages, but the pages don't load, and it doesn't seem to be working. I've tried using it with [Disable Content-Security-Policy](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en) unsuccessfully. When loading any page on linkedin.com while the Chrome extension is active, many of these errors can be seen in the console:

<img width="847" alt="Screen Shot 2019-03-20 at 11 10 27 PM" src="https://user-images.githubusercontent.com/8534941/54731581-6a608000-4b65-11e9-81c8-27cb96e97a6a.png">

When inspecting these `<img>` elements, they are actually LinkedIn-generated HTML like `<img src="data:image/gif;...`, but for some reason, they fail their Content Security Policy when artoo.js is active. 

Is this part of the LinkedIn anti-scrapping effort (not sure what it would be) or am I doing something wrong?

**Comment by Yomguithereal** [comment]
I am not sure about what happens but, before I try to investigate further, can you try using artoo in firefox when CSP are shunted (can be done in config in Firefox, no need for an extension). My guess is that the chrome extension you are using maybe is messing some corner cases up.

**Comment by younkim** [comment]
@Yomguithereal Using artoo.js on Firefox would be through the bookmarklet method?

BTW, I tried the bookmarklet method on Chrome along with Disable Content-Security-Policy, and that works. It's just that I have a lot of pages I'd like to scrape while I'm on it on the browser, and I'd like the extension to be on automatically.

**Comment by Yomguithereal** [comment]
Yes, Firefox through the bookmarklet.

> and I'd like the extension to be on automatically.

If I recall correctly, if you activate the extension on Chrome, artoo is loaded automatically on each page you visit.

**Comment by younkim** [comment]
@Yomguithereal You're right. The extension persists through pages unless a refresh is made. The bookmarklet method works great, thanks!
