### ISSUE TITLE
Help with ajaxSpider debugging

### ISSUE THREAD

**Issue by suntong** [medialab/artoo#289]
I need to use `ajaxSpider` to retrieve [linked page](https://rarbg.to/torrent/jcru6xm)s from an [index page](https://rarbg.to/torrents.php?search=survivor+S37+WEBRip.x264-ION10&category%5B%5D=18&category%5B%5D=41&category%5B%5D=49).
I found a good starting script at #192, however, I'm having a hard time putting them together. 

I first go to the [linked page](https://rarbg.to/torrent/jcru6xm) and try `artoo` with 

`artoo.scrapeOne('table.lista > tbody > tr:nth-child(1) > td.lista > a:nth-child(3)', {url: 'href'});`

and get exactly what I want.

but when putting it into  `ajaxSpider` all I get are `undefined`s. What I missed? 
Here is my script for the  [index page](https://rarbg.to/torrents.php?search=survivor+S37+WEBRip.x264-ION10&category%5B%5D=18&category%5B%5D=41&category%5B%5D=49):

```js
// Retrieving the urls
var urls = artoo.scrape('tr.lista2 > td.lista:nth-child(2) > a:first-child', 'href');

// Showing urls
//console.log(urls);

// Deploying an ajax spider
artoo.ajaxSpider(
  // Feeding the spider with our urls
  urls,

  // Registering some parameters
  {
    // We want the html to be parsed with jQuery
    jquerify: true,

    // Function executed at each step
    process: function($page, i) {
      artoo.log.debug('Fetching page n°' + i);

      // Returning the results of scraping the page
      // TODO: adjust the scraping to fit your tastes
      return $page.scrapeOne('table.lista > tbody > tr:nth-child(1) > td.lista > a:nth-child(3)', {magnet: 'href'});
    },

    // A limit for dev purposes (remove it if you want everything)
    limit: 2,

    // Callback for when we are done
    done: function(results) {
      // Inform we are done with a sound
      artoo.beep('original');

      // Showing results
      console.log(results);

      // let's download our data
      artoo.saveCsv(results, 'results.csv');
    }
  }
);
```

Please help. Thx!

**Comment by Yomguithereal** [comment]
Hell @suntong,

Jquerify does not work very well on this website because it is quite badly coded. But you can try the following:

```js
// Retrieving the urls
var urls = artoo.scrape('tr.lista2 > td.lista:nth-child(2) > a:first-child', 'href');

// Showing urls
//console.log(urls);

// Deploying an ajax spider
artoo.ajaxSpider(
  // Feeding the spider with our urls
  urls,

  // Registering some parameters
  {
    // We want the html to be parsed with jQuery
    jquerify: false,

    // Function executed at each step
    process: function($page, i) {
      console.log($page)
      $page = artoo.$(artoo.$.parseHTML($page));
      artoo.log.debug('Fetching page n°' + i);
      // Returning the results of scraping the page
      // TODO: adjust the scraping to fit your tastes

      return artoo.scrapeOne(
        $page.find('table.lista > tbody > tr:nth-child(1) > td.lista > a:nth-child(3)'),
        {magnet: 'href'}
      );
    },

    // A limit for dev purposes (remove it if you want everything)
    limit: 1,

    // Callback for when we are done
    done: function(results) {
      // Inform we are done with a sound
      artoo.beep('original');

      // Showing results
      console.log(results);

      // let's download our data
      artoo.saveCsv(results, 'results.csv');
    }
  }
);
```

But your inner scraper on `'table.lista > tbody > tr:nth-child(1) > td.lista > a:nth-child(3)'`  does not work and I fear the site may be returning a different HTML when using ajax. You will maybe need to spoof some xhr params.

**Comment by suntong** [comment]
Ah, *"Jquerify does not work very"*, I'd never thought of that, :) Thanks for the html treat and `console.log($page)` trick. which would be very useful for other tasks. 

> the site may be returning a different HTML when using ajax

Indeed. I did some further reading and found 

**Fake XHR with Sinon.JS**  
https://sinonjs.org/releases/latest/fake-xhr-and-server/

Can we make use of it (or anything that can fakes native `XMLHttpRequest`) within `artoo`? If it is possible, I can ask in a new thread, else, it's OK as well  -- I'll just give up scrapping this site, :).

**Comment by suntong** [comment]
I presume the answer is *"no"*, which is fine.
