### ISSUE TITLE
how to take the sniffer off / how to use artoo.ajaxSniffer.off

### ISSUE THREAD

**Issue by brainmixxx** [medialab/artoo#290]
I have trouble to take off a sniffer. Could someone help me?

what i did:

```
artoo.ajaxSniffer.after(function(req, res) {
  //console.log("req: " + JSON.stringify(req));
  if (req.url.search(/event\/[0-9]+\/json/) != -1) {
    console.log('response data: ');
    console.log(res.data);
    //artoo.savePrettyJson(res.data);
  }
}) 

// code for actions

// take off the sniffer
artoo.ajaxsniffer.off(???) // how to take it now off?

**Comment by Yomguithereal** [comment]
Hello @brainmixxx. This event emitter is not very elaborate so to be able to "off" your handler, you just need to pass the function to the `off` method:

```js
var handler = function(req, res) {
  //console.log("req: " + JSON.stringify(req));
  if (req.url.search(/event\/[0-9]+\/json/) != -1) {
    console.log('response data: ');
    console.log(res.data);
    //artoo.savePrettyJson(res.data);
  }
}

artoo.ajaxSniffer.after(handler) 

// code for actions

// take off the sniffer:
artoo.ajaxsniffer.off(handler)
```

Note that if every handler was offed, artoo will release its parasites over the xhr connections. Also note that I don't think those sniffers would work with the more recent `fetch` calls.

**Comment by brainmixxx** [comment]
Hello @Yomguithereal thank you for the fast reply. The sniffer itself works. When I try your code I have following error:

```
artoo-latest.min.js:2 Uncaught Error: artoo.ajaxSniffer.off: trying to remove an inexistant listener.
    at t.off (artoo-latest.min.js:2)
    at <anonymous>:2:19
```

**Comment by Yomguithereal** [comment]
It seems you are trying to off a handler function that was not passed to the sniffer. Maybe you are trying to remove the same listener more than once?

**Comment by brainmixxx** [comment]
no, I did not. But at the moment it is important that the sniffer is on and not to make them off.

Thank you for your help!
