### ISSUE TITLE
ajaxSniffer.after method is not working

### ISSUE THREAD

**Issue by devmertsert** [medialab/artoo#306]
ajaxSniffer.after method doesn't work. when request is sent, ajaxSniffer.after method can't catch it. What should i do? is there another way to catch requests?

**Comment by Yomguithereal** [comment]
artoo's ajaxSniffer was developed at a time `fetch` was not a thing yet, as we only had `XMLHTTPRequest` related stuff. So unfortunately I would say this piece of code is probably outdated nowadays, which is probably why the sniffer does not work in your case. 

Maybe it is possible to monkeypatch `fetch` but I did not investigate much about it and I don't have time to do so soon. If you want you can try and investigate please feel free to open a PR on the subject and I will review it.

**Comment by devmertsert** [comment]
Firstly i want to correct my sentence. It is not working on some sites not all. Because it is blocked by that sites. Sorry for that. And i am trying to fix this. i will inform you. And i will check monkeypatch. Thanks for your answer

**Comment by Yomguithereal** [comment]
This is because of CSP rules some websites are enforcing through response headers. You might want to check how to disable browser security wrt CSP or use some browser extension such as: https://chrome.google.com/webstore/detail/allow-csp-content-securit/hnojoemndpdjofcdaonbefcfecpjfflh

**Comment by devmertsert** [comment]
Yes, that was my problem but i fixed it. I found an extension as you said. There is no problem for now. Thank you
This is the extension:
https://chrome.google.com/webstore/detail/scriptautorunner/gpgjofmpmjjopcogjgdldidobhmjmdbm
